### ISSUE TITLE
provide more info / context for taxa in interactions browser

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions.github.io#10]
as discussed with @jhammock and Michele Weber @mxweber :

Currently, the browser pages contains scientific names of taxa involved in interactions. To further inform users about the nature of the taxon, more information would be helpful. 

One way to do this could be to show an info box appears when hovering / clicking on taxon name wherever one appears on the page. The info box would contains a thumbnail, scientific name, common name (if available) and link to EOL taxon page (or other when available).

**Comment by coding46** [comment]
Base implementation @see http://www.globalbioticinteractions.org/widget.html

**Comment by jhammock** [comment]
pretty! thumbnails make everything better.
