### ISSUE TITLE
Arctos getting a 404 when looking for GloBI stuff

### ISSUE THREAD

**Issue by Jegelewicz** [globalbioticinteractions/globalbioticinteractions.github.io#101]
@jhpoelen see https://github.com/ArctosDB/arctos/issues/4998#issue-1359316806

**Comment by jhpoelen** [comment]
@Jegelewicz thanks for letting me know. I investigated and reported in https://github.com/ArctosDB/arctos/issues/4998#issuecomment-1234852754 . Waiting for your reply.

**Comment by jhpoelen** [comment]
closing this issue as duplicate of https://github.com/ArctosDB/arctos/issues/4998#issuecomment-1234852754
