### ISSUE TITLE
When linking to Scholia, do not specify the profile type

### ISSUE THREAD

**Issue by Daniel-Mietchen** [globalbioticinteractions/globalbioticinteractions.github.io#110]
Currently, per https://github.com/globalbioticinteractions/globalbioticinteractions.github.io/commit/bc3688a0c3e7a1dc0cf13a86b0c2b224dd9af79e , GloBI links to Scholia's topic profile, and this is hard-coded.
This can be removed, since Scholia has a way to figure out which profile type to show for a given QID.

**Comment by jhpoelen** [comment]
@Daniel-Mietchen thanks for helping to improve the linking from GloBI to Scholia.
