### ISSUE TITLE
suggest to include ability to search by source, interaction types and target

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions.github.io#12]
as discussed with @jhammock and Michele Weber @mxweber :

Suggest to include a way to specify source , target and interaction type to restrict interactions of interest. 

Included a rough sketch of one (of the many) ways to provide this functionality. Note the proposed purple search fields on top of the columns.

![screen shot 2015-02-13 at 11 46 01 am](https://cloud.githubusercontent.com/assets/1084872/6194121/0c89f690-b376-11e4-815f-63438270db76.png)

**Comment by coding46** [comment]
Implemented. @see http://www.globalbioticinteractions.org/widget.html
