### ISSUE TITLE
add higher taxon order icon to species interaction browser

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions.github.io#14]
as discussed with @jhammock and Michele Weber @mxweber:

Currently, scientific names are used to indicate interacting taxa in the interaction browser. To give an indication of the kind of taxa (e.g. birds, insects, mammals), icons are used, similar to what iNaturalist is using (see screenshot taken from http://www.inaturalist.org/taxa/7079-Oxyura-jamaicensis). 

@pleary @kueda would it be ok if we recycle / re-use the pretty iconic taxa you use on iNaturalist https://github.com/inaturalist/inaturalist/tree/master/app/assets/images/iconic_taxa ? If so, how can we best attribute iNat for this? 

![screen shot 2015-02-13 at 11 53 59 am](https://cloud.githubusercontent.com/assets/1084872/6194226/2343d0bc-b377-11e4-887d-b77e7634afb4.png)

**Comment by kueda** [comment]
Hm, good question. Personally I'd be ok with it if you were providing links back to iNat (which it doesn't seem like you're doing), but I am no longer personally the copyright holder for those works. The CA Academy of Sciences is. I'm also not entirely sure how a software license like the MIT license applies to creative works nested within a software repository like this. The license specifically refers to "the SOFTWARE," and while these images are used in the software, they are not themselves software, so it's unclear to me if the terms of the license applies to them.

So... I'd hold off for now. Let me ask around.

**Comment by jhpoelen** [comment]
Sounds like a plan: let me know how it goes. Also, I just created another issue https://github.com/jhpoelen/eol-globi-data/issues/115  - I think it would be kind of nice to let folks now that their data is being used. All iNaturalist observations that are discovered by GloBI through the iNat API are linked back to the source. Let me know if you have any other ideas to make sure that folks get credit for sharing their observations.

**Comment by kueda** [comment]
So I talked to the legal team. When they acquired iNaturalist the Academy also trademarked the bird icon, since we use it in our logo, so use of the bird icon requires some form of license from the Academy, *unless* you are using it as a part of the iNaturalist web application, whose source code repository includes the bird icon file. It might be legally permissible to use the other icons, but I think it sounds like more trouble than it's worth. I'd just find some other icons. Sorry.

**Comment by jhpoelen** [comment]
Thanks for taking the time to look into this.

**Comment by jhammock** [comment]
(the trick seems to be finding an existing free set that covers all the groups you will want. Depending on the level of professionalism/seriousness/consistency you want, well, these artists look fun:
http://www.iconarchive.com/artist/imil.html
http://www.iconarchive.com/artist/icondigest.html
http://www.iconarchive.com/artist/t-motoyama.html)

**Comment by jhpoelen** [comment]
reopening issue because @mariestuder and @KatjaSchulz suggested http://phylopic.org/ and https://pixabay.com/en/

**Comment by jhpoelen** [comment]
Hi @MarieStuder and @KatjaSchulz , could you please help select icons from phylopic related to groups as listed in #41 using http://phylopic.org/image/browse/ ?

I might not be the best person to select suitable icons. If you find one, please attach the image url to this issue (e.g. http://phylopic.org/assets/images/submissions/e5b0cde8-beab-48dc-b77c-d48b16c6a05e.thumb.png).

Here's the groups:
.Protozoa
.Plantae
.Fungi
.Animalia
.Mollusca
.Arachnida
.Insecta
.Amphibia
.Reptilia
.Aves
.Mammalia
.Actinopterygii
.Chromista 

Thanks!

**Comment by jhammock** [comment]
Arg. That website is fun but does not support traffic well. I would suggest not leaving the main browser page and just copying image url from there, at least for discussion. btw, I like these, though for the microbes I don't know how to assign them:

http://phylopic.org/assets/images/submissions/21d91974-1f16-47ee-97d0-dd44dfb76eef.thumb.png
http://phylopic.org/assets/images/submissions/9fa6f3b7-efda-49ce-a119-eb6070d77a75.thumb.png
http://phylopic.org/assets/images/submissions/febb8ca1-4f28-4d6f-8e78-d7d3c568c893.thumb.png
http://phylopic.org/assets/images/submissions/083d187a-5b1b-478c-980b-31ad91f865fa.thumb.png
http://phylopic.org/assets/images/submissions/bc7b7eb5-c208-4a24-9287-eaf5118e8887.thumb.png
http://phylopic.org/assets/images/submissions/b6400f39-345a-4711-ab4f-92fd4e22cb1a.thumb.png
http://phylopic.org/assets/images/submissions/1eb7433a-4943-4220-aa66-a658b272f23c.thumb.png
http://phylopic.org/assets/images/submissions/6c6c5073-2383-40fb-9824-c6a8ed27badc.thumb.png
http://phylopic.org/assets/images/submissions/ee764929-c865-44f6-b5db-b4e7d5693d1a.thumb.png
http://phylopic.org/assets/images/submissions/dffda000-77cb-4251-b837-0cd2ab21ed5b.thumb.png
http://phylopic.org/assets/images/submissions/90e1c28f-dd6f-4b1c-b263-91d208610458.thumb.png
http://phylopic.org/assets/images/submissions/244be3ea-0fe5-45b6-b04e-1bd914489f95.thumb.png
http://phylopic.org/assets/images/submissions/e5b0cde8-beab-48dc-b77c-d48b16c6a05e.thumb.png
http://phylopic.org/assets/images/submissions/44fa6ec0-6bad-42bd-ae91-48d00c9b035c.thumb.png (finally! Not much love for arachnids on this platform.)

For many groups the pickings are thin, but there are lots of options for birds, mammals and insects... 

Displacement activity? Moi?

**Comment by jhpoelen** [comment]
Nice! I've but them in a list . . . taking a first stab at naming them in a bit

| taxonomic group | image | 
--- | --- 
some name|![image](http://phylopic.org/assets/images/submissions/9fa6f3b7-efda-49ce-a119-eb6070d77a75.thumb.png)
some name|![image](http://phylopic.org/assets/images/submissions/febb8ca1-4f28-4d6f-8e78-d7d3c568c893.thumb.png)
some name|![image](http://phylopic.org/assets/images/submissions/083d187a-5b1b-478c-980b-31ad91f865fa.thumb.png)
some name|![image](http://phylopic.org/assets/images/submissions/bc7b7eb5-c208-4a24-9287-eaf5118e8887.thumb.png)
some name|![image](http://phylopic.org/assets/images/submissions/b6400f39-345a-4711-ab4f-92fd4e22cb1a.thumb.png)
some name|![image](http://phylopic.org/assets/images/submissions/1eb7433a-4943-4220-aa66-a658b272f23c.thumb.png)
some name|![image](http://phylopic.org/assets/images/submissions/6c6c5073-2383-40fb-9824-c6a8ed27badc.thumb.png)
some name|![image](http://phylopic.org/assets/images/submissions/ee764929-c865-44f6-b5db-b4e7d5693d1a.thumb.png)
some name|![image](http://phylopic.org/assets/images/submissions/dffda000-77cb-4251-b837-0cd2ab21ed5b.thumb.png)
some name|![image](http://phylopic.org/assets/images/submissions/90e1c28f-dd6f-4b1c-b263-91d208610458.thumb.png)
some name|![image](http://phylopic.org/assets/images/submissions/244be3ea-0fe5-45b6-b04e-1bd914489f95.thumb.png)
some name|![image](http://phylopic.org/assets/images/submissions/e5b0cde8-beab-48dc-b77c-d48b16c6a05e.thumb.png)
some name|![image](http://phylopic.org/assets/images/submissions/44fa6ec0-6bad-42bd-ae91-48d00c9b035c.thumb.png )

**Comment by jhpoelen** [comment]
@jhammock am a bit puzzled by the first four . . . could you please help?

**Comment by jhammock** [comment]
The first four are microbes; I will poke around to see what distinguishing features should be displayed for a protozoan- I'm not sure if we have one in there or not. The fourth is a flower! I meant it as another alternative for Plantae, but if you didn't recognize it, I'd say the fifth must be better.

**Comment by mariestuder** [comment]
Thanks Jen for pulling these out!

FWIW, I recognized 4 as a flower and thought you were distinguishing between flowering plants (Angiospermae or Magnoliophyta) and #5 as potentially other.  If we're putting all plants together (which is fine by me) then I guess #5 is more recognizable.

**Comment by jhammock** [comment]
Aha! http://cmr.asm.org/content/13/1/35/F1.expansion.html

All three microbes might be fine, but #3 is distinctive, and apparently a flagellated protozoan.

**Comment by mxweber** [comment]
The first 3 are definitely protists - very cool! Do you need me to figure
out which are which?

Looks like you need something for "protista" and "Chromista"? (Those two
names are somewhat overlapping/controversial)

-m.

**Comment by jhammock** [comment]
No, I think apart from the Chromista we weren't going to subdivide the protists any further. I was actually thinking a macro for chromista, but I somehow dropped my selection from the list, oops.
What do we think of this?
http://phylopic.org/assets/images/submissions/21d91974-1f16-47ee-97d0-dd44dfb76eef.thumb.png

Also, if we need a general purpose "Animalia" icon, how about a recognizable group not too closelt related to those already represented? A nice jellyfish
http://phylopic.org/assets/images/submissions/e4d57d67-c144-457a-877b-34faaaa16ed2.thumb.png

or an echinoderm?
http://phylopic.org/assets/images/submissions/f95dea80-ead0-4948-8ec7-14edf912ea87.thumb.png

**Comment by mariestuder** [comment]
Hummm....that first image looks more like a flower to me!  Funny things, these silhouettes! 

I'm partial to the echinoderm.

**Comment by mxweber** [comment]
Of all the discussions about the "groups" that make up "protists" I would
never single out Chromista. It is polyphylectic and the definition (which
groups are included) varies depending on who you talk to. It is a difficult
rank to define. Some of the more specific names are more robust, i.e.:
Rhizaria, Excavates, etc.

It is just really hard to come up with a robust hypothesis for the
evolution of of different groups single celled euks. Is there some reason
we need Chromista? Does EOL have an official stance on this part of the ToL?

And I agree with Marie that
http://phylopic.org/assets/images/submissions/21d91974-1f16-47ee-97d0-dd44dfb76eef.thumb.png
looks
like a flower!

-m.

**Comment by jhammock** [comment]
EOL doesn't have an official opinion about Chromista; I think these groupings are in imitation of iNaturalist, where the Chromista group makes more sense- if you can see it with the naked eye, it's a seaweed sort of thing, and Chromista is as good a name as any? Anyway, for GloBI purposes, should it be just Protists? Or maybe Protozoans and Algae, to be user friendly?

**Comment by jhammock** [comment]
(I mean either Protists or "protozoans & algae", still together as one group, sorry. Doing that would obviate the need for the flowery seaweed image, too...)

**Comment by mxweber** [comment]
I was just writing back about how "algae" is also problematic… Am I being
overly fussy here?!

I think "protozoa & algae" will work out great. It is clear that the group
is diverse. It alludes to the polyphyly problem without diving in. Any of
those icons should work. And the seaweed/flower confusion is avoided!

Of course it is giving the poor ignored single celled euks the short end of
the stick again, but that is nothing new!

-m.

**Comment by kueda** [comment]
Speaking for iNat, we try really, really, really hard not to argue about taxonomic issues like whether or not Chromista deserves to be a taxon despite its polyphyly (which displeases systematists) and its complete lack of use among naturalists. We try to avoid such discussions by following other taxonomic authorities, and in the case of very high level classifications like this, we're mostly following Catalogue of Life, who supported Chromista as a kingdom back in [2013](http://www.catalogueoflife.org/annual-checklist/2013/browse/tree/id/13021718), and continue to do so in [2015](http://www.catalogueoflife.org/col/browse/tree/id/3520fbd4604c0d9890e037678776bfd2).

Anyway, just some history. Thanks for the http://phylopic.org link! I hope they fix their technical issues b/c it seems like a neat site.

**Comment by jhpoelen** [comment]
Thanks everyone!  . . . I created a new project for this: taxaprisma - colors and silhouettes for taxa . Please let me know if the table is getting close: https://github.com/jhpoelen/taxaprisma/ . @jhammock which image did you have in mind for the Fungi? Happy to add / remove categories as we progress.

**Comment by jhpoelen** [comment]
btw - if anyone has a better name for the project, please let me know.

**Comment by coding46** [comment]
Introduced by 4d7e2922ee3235d064f1a27778f30c9e218152fd 

demo at http://www.globalbioticinteractions.org/browse/index.html

... and for the package name 'taxaprisma' - awesome! :)

**Comment by jhpoelen** [comment]
here's a screenshot of what @coding46 helped build using taxaprisma.
![screen shot 2015-08-28 at 7 20 27 pm](https://cloud.githubusercontent.com/assets/1084872/9560131/f54d394a-4db9-11e5-8191-ba1e7099ade2.png)

**Comment by mariestuder** [comment]
The silhouette icons look good and they are helpful to the end-user to quickly identify the category of taxon they are looking at.

In this search
![screen shot 2015-09-03 at 5 32 38 pm 2](https://cloud.githubusercontent.com/assets/11097758/9671604/077ec7f8-5262-11e5-9b86-89af15252fc9.png)

The silhouettes of the organisms on the right (e.g., the prey) show up, but the predator (e.g. Great White Shark) doesn't.  Could/should a silhouette also be added to the Great White Shark?  It works for other searches, just not this one.

**Comment by jhpoelen** [comment]
@mariestuder thanks for sharing your comment. If you, @jhammock or someone your know can pick a nice silhouette from http://phylopic.org (or similar) for sharks and rays (Elasmobranchii), I can add it to https://github.com/jhpoelen/taxaprisma and incorporate is into the interaction browser.
