### ISSUE TITLE
update hairball and bundle diagram when new search parameters are entered

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions.github.io#15]
Whenever spatial, taxonomic or interaction type parameters are updated, all related views of the interaction data should be updated accordingly.

**Comment by jhpoelen** [comment]
additionally, update the map to highlight the selected interactions at recorded observation locations. Also, whenever an interaction is selected, these are also highlighted interactions in the bottom visualizations.

**Comment by jhpoelen** [comment]
suggest to look into ```events``` package - https://www.npmjs.com/package/events

**Comment by jhpoelen** [comment]
suggest to show extra information about an interaction selected in the bottom two panels using the taxon interaction search widget / images / names etc.

**Comment by coding46** [comment]
Fixed by d3c03d7730182d1a68dd4501eba675456c567d3a
