### ISSUE TITLE
include link in interaction widget to download interaction data

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions.github.io#17]
suggested by @KatjaSchulz  : 

After getting a result in the taxon search widget, a download button should be available to retrieve all observations / interaction records associated with the results. 

For instance, a search for birds (Aves) eating insects (Insecta) as a specific location would have a download button pointing to:

http://api.globalbioticinteractions.org/interaction.csv?sourceTaxon=Aves&targetTaxon=Insecta&interactionType=preysOn&type=csv&includeObservations=true&bbox=-125.53344800000002,32.750323,-114.74487299999998,41.574361&field=source_taxon_name&field=source_taxon_external_id&source_taxon_path&field=interaction_type&field=target_taxon_name&field=target_taxon_external_id&field=target_taxon_path&field=latitude&field=longitude&field=study_citation&field=study_url&field=study_source_citation

**Comment by coding46** [comment]
Introduced and implemented in https://github.com/jhpoelen/eol-globi-js/commit/aeb7ee60f4dc865ebcfcd8d488441d894fedb347

@see http://www.globalbioticinteractions.org/browse for demo
