### ISSUE TITLE
include number of distinct source and target taxa in interaction widget result

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions.github.io#18]
as suggested by @KatjaSchultz : 

When showing search results, include the number of distinct source and target taxa in the search results to inform the user on the richness of the results. Something along the lines of: 35 birds (Aves) taxa found and 54 insects (Insecta) taxa found.

![screen shot 2015-03-13 at 11 49 20 am](https://cloud.githubusercontent.com/assets/1084872/6645130/1667656e-c977-11e4-84ef-f7e529e4d844.png)

**Comment by coding46** [comment]
Introduced and implemented by https://github.com/jhpoelen/eol-globi-js/commit/54c6922012de86a44d24a7c72b56501ad62aba5e

@see http://www.globalbioticinteractions.org/browse for demo

**Comment by jhpoelen** [comment]
Thanks for adding this so quickly!
