### ISSUE TITLE
switch taxonomic search suggestion in search widget to use the api

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions.github.io#19]
Currently, the search widget is using the observation data to suggest names. 

To simply the name lookup, suggest to use the methods available through the api http://api.globalbioticinteractions.org/findCloseMatchesForTaxon/Mencsh . 

@coding46 I've updated API to use the name fields / selectors just like those used in interaction queries.

**Comment by coding46** [comment]
Is there a way to change (or add a method) the api in a way that that the query value is a get parameter?

F.x.:
```
http://api.globalbioticinteractions.org/findCloseMatchesForTaxon?q=Mencsh
```

As our suggestion widget works out-of the box with get parameters instead of url path parts it would be really easy to implement this feature without touching the input widget.

**Comment by jhpoelen** [comment]
Thanks for the suggestion  . . . you can now also use http://api.globalbioticinteractions.org/findCloseMatches?taxonName=Mencsh  . Would that help?

**Comment by coding46** [comment]
Ah, nice, this will do the trick.

**Comment by coding46** [comment]
Introduced and implemented by https://github.com/jhpoelen/eol-globi-js/commit/ddd518ba04dae1672f710731cec0ffc0b24b1878

@see http://globalbioticinteractions.org/browse for demo

**Comment by jhpoelen** [comment]
@coding46 for some reason, I could not get the autocomplete to work in the current browser (see screenshot). Also an error seems to be occurring ```TypeError: this.data(...) is undefined```. Let me know what I can do to see the functionality you've implemented.
![Uploading Screen Shot 2015-03-18 at 2.16.03 PM.png . . .]()

**Comment by coding46** [comment]
Fixed by https://github.com/jhpoelen/eol-globi-js/commit/50d994dedae1674e177c0c6a449c237b1fb39f64
Was an issue with timing caused by the more complex dom in the browse view.

**Comment by jhpoelen** [comment]
@coding46 Thanks, works great now!
