### ISSUE TITLE
add placeholder image for species w/o image

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions.github.io#20]
As discussed last week: Not all taxa have images associated to them, and currently this shows up as a broken image link. Suggest to place an empty image (or any html element) or placeholder image whenever image is not available.

![screen shot 2015-03-18 at 12 22 03 pm](https://cloud.githubusercontent.com/assets/1084872/6719678/900e12e0-cd79-11e4-9ae6-8e2b38b0eab4.png)

**Comment by jhpoelen** [comment]
Suggest to not render the image at all if no URL is available - keeps it simple. This would still leave the option for others to embed a no-image image at some point in time.

**Comment by coding46** [comment]
Introduced by 2efef5a82bd1bbc679ce73b188ebb051d33841c7
