### ISSUE TITLE
ensure that widget allows for non-geolocated interaction data

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions.github.io#21]
as discussed with @jhammock .

**Comment by jhpoelen** [comment]
Just confirmed that widget works without specifying a location / bounding box.

For example see:
http://www.globalbioticinteractions.org/widget-no-location.html

**Comment by jhpoelen** [comment]
@jhammock - without specifying location constraints csv download files might contain empty lat/lng pairs. Some data providers do not have lat / lng pairs available.

**Comment by jhammock** [comment]
yes, that sounds right. If the widget is deployed that way, we'll be letting people in for the possibility of more incomplete metadata. Buyer beware!
