### ISSUE TITLE
taxon selector uses initial spatial selection only

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions.github.io#28]
To reproduce:

1. select a spatial area 
1. click on "show interactions" to update the visualizations
1. enter a search clause in the taxon selector 
1. change spatial area, click on "show interactions"
1. enter same search clause in taxon selector

expected result:
the taxon selector results are different, because of the change in spatial selection.

actual result:
taxon selector result is same - appears that the spatial search parameter are not applied to the taxonomic interaction search widget.

**Comment by coding46** [comment]
Fixed by 548ab1eacd457c9fcea280ffaf70f4d0c9a6650b

Change of spatial date leads to change of request with correctly applied data.
