### ISSUE TITLE
globi-search tests are failing (and not executing on travis)

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions.github.io#31]
Hi @coding46 - I was working on globi-search module and noticed that the TypeSelector test (since renamed to ```test/addRemoveOptions.js``` failed due to (what I believe is)  a DOM timing issue. Unfortunately, travis is not picking up the tests because it doesn't seem to install globi-search properly in the pre-install phase.

Let me know if you can reproduce the test failures. If so, please fix them.

**Comment by coding46** [comment]
Fixed d619ebb10197450aa6ce1c9b617c3b447c1a14ac
