### ISSUE TITLE
globi-search tests not executing on travis

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions.github.io#32]
see #31 for related issue. 

It seems that globi-search module is not being installed properly on travis for some reason. After several attempts to fix the issue, I decided to write this issue so that we don't forget. 

The install files on the preinstall phase:
(see https://travis-ci.org/globalbioticinteractions/globalbioticinteractions.github.io/builds/75522883 ).

```
> npm cache clean & npm install ./node_modules/globi-*
untar error /home/travis/.npm/globi-search/0.0.2/package.tgz
```

**Comment by jhpoelen** [comment]
@coding46 looks like the issue was: ```npm install ./node_modules/globi-*```. This didn't cause an issue on mac os, but on travis ```npm install node_modules/globi-*``` worked. 

Also the ```browser -t brfs ...``` was redundant because of:

```
"browserify": {
    "transform": [
      "brfs"
    ]
  }
```

in ```package.json```

**Comment by jhpoelen** [comment]
PS successful travis build: https://travis-ci.org/globalbioticinteractions/globalbioticinteractions.github.io/builds/75692761 .

**Comment by coding46** [comment]
Nice catch! Great!

**Comment by jhpoelen** [comment]
@coding46 thanks - it seems that it is broken again though . . . can't reproduce locally:

```Error: Cannot find module '../globi-search/lib/Mediator.js' from '/home/travis/build/globalbioticinteractions/globalbioticinteractions.github.io/node_modules/globi-wheel'
    at /home/travis/build/globalbioticinteractions/globalbioticinteractions.github.io/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/home/travis/build/globalbioticinteractions/globalbioticinteractions.github.io/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/travis/build/globalbioticinteractions/globalbioticinteractions.github.io/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /home/travis/build/globalbioticinteractions/globalbioticinteractions.github.io/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:95:15)
```
