### ISSUE TITLE
[FEATURE] Connect visualisations with search widget

### ISSUE THREAD

**Issue by coding46** [globalbioticinteractions/globalbioticinteractions.github.io#33]
If one clicks on a taxon node in dependency wheel / bundle view ... this selection should trigger a new search with this taxon and the most general interaction type.

**Comment by coding46** [comment]
Implementation hint:
- jquery-tokeninput (TaxonSelector) has methods for clearing the input field and adding tokens into it. This triggers an event we're currently listen to.
- in TypeSelector we're currently missing a method for doing the same stuff as described for TaxonSelector

Given those two are there the search get's triggered automagically. :)

**Comment by jhpoelen** [comment]
In review session, I proposed this feature to and it seemed like the current search functionality is sufficient (at least for now...).
