### ISSUE TITLE
describe purpose of interaction browser panels in text 

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions.github.io#42]
@mariestuder suggested to include a description for each of the widgets used in the interaction browser (particularly the bundle/ hairball visualizations) to help the user understand their purpose.

**Comment by jhpoelen** [comment]
@coding46 suggested to have an info button that shows with info text when clicked.

**Comment by jhpoelen** [comment]
panels now have "?" that link to relevant section on our [wiki](../wiki).

![screen shot 2015-08-26 at 7 57 07 pm](https://cloud.githubusercontent.com/assets/1084872/9511547/b1f5623c-4c2c-11e5-9895-4d50b9874813.png)

**Comment by jhpoelen** [comment]
@mariestuder please re-open this issue if you have some suggestions on this.

**Comment by mariestuder** [comment]
This is a huge improvement.  People can now get a sense of what each of these diagrams mean.  Here are some comments -- either for now or the future -- for the panels or the wiki explanation.

1. Interaction Search.  Looks good.

2. Map -- can you add a description of the map and the various icons to the Wiki similar to what you have done for the other panels?  The "area picker" is mentioned under the section for the Interaction search, but it's not clear this belongs to the Map section. 

3. Hairball 
Wiki description: https://github.com/globalbioticinteractions/globalbioticinteractions.github.io/wiki.  Add a sentence clarifying what the direction of the arrows mean.

The arrows in the hairball:  to me, they seem backward.  I expect to see the direction of the arrow going from prey to predator, for example - or "up" the food chain:  Primary producer > primary consumer > secondary consumer > tertiary consumer > apex consumer.  

Either way, it would be very good to be explicit about what the direction of the arrow means.

4. Bundle diagram (https://github.com/globalbioticinteractions/globalbioticinteractions.github.io/wiki#bundle-diagram).  Add a sentence or graphic that identifies which colors correspond to which taxonomic group (i.e., Blue = Aves, etc)

**Comment by jhpoelen** [comment]
Thanks for your suggestions . . . I've applied some changed to https://github.com/globalbioticinteractions/globalbioticinteractions.github.io/wiki . Please feel free to edit the page (you should have write access) if you'd like add / edit.

**Comment by jhpoelen** [comment]
Also, I opened a separate issue for the direction of interactions: https://github.com/globalbioticinteractions/globalbioticinteractions.github.io/issues/55
