### ISSUE TITLE
when searching for Amphibia, two Amphibia suggestions appear where one “works better” than the other.

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions.github.io#43]
As observed by @jhammock review meeting:

when searching for Amphibia, two Amphibia suggestions appear where one “works better” than the other.

**Comment by jhpoelen** [comment]
Turns out that the interaction is cannibalistic . . .  
http://www.globalbioticinteractions.org/#sourceTaxon=Dicamptodon%20tenebrosus&interactionType=eats

Perhaps in the hairball we can have little loops pointing to itself, or perhaps just leaving out. @jhammock any ideas?

**Comment by jhammock** [comment]
Cannibalism counts. We can leave it as is, but if a little loopy cannibal arrow is easy, I would want it for clarification.

**Comment by jhpoelen** [comment]
previous two comments where related to issue #47 . Moving comments.

**Comment by jhpoelen** [comment]
I've attempted to reproduce this issue, but could not. @jhammock please re-open this issue if you can reproduce this.
