### ISSUE TITLE
change result list headers 

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions.github.io#46]
currently the result list headers look like:

![screen shot 2015-08-20 at 2 58 51 pm](https://cloud.githubusercontent.com/assets/1084872/9396767/018d7324-474c-11e5-86e4-9e47fa0c43b9.png)

@mariestuder suggested to change to something like:

```
taxon                    interacts with                       taxon
(136 distinct)         (3711 interactions)              (379 distinct)
```

where the middle column reflects the currently selected interaction type

**Comment by jhpoelen** [comment]
hi @coding46 thanks for taking a stab at this. I am re-opening because the result header is not quite as expected:
```
taxon                    interacts with                       taxon
(136 distinct)         (3711 interactions)              (379 distinct)
```

After your recent changes, the header was: 

![screen shot 2015-08-24 at 3 34 44 pm](https://cloud.githubusercontent.com/assets/1084872/9454292/ab885a5c-4a75-11e5-8339-527460d46b51.png)

It also appears that the download link text is now gone. Suggest to re-add the download link text (e.g. "download csv") in addition to the expected header. 

Thanks!

**Comment by coding46** [comment]
Please take a look at 71df53f and provide feedback if this works as planned.

**Comment by jhpoelen** [comment]
Looks nice! Thank you for your quick response.
