### ISSUE TITLE
add infobox whenever a taxon node is selected 

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions.github.io#48]
@mariestuder suggested to add a taxon info box in bundle/ hair visualization whenever a taxon node is hovered over / selected. This is to provide some taxonomic context of the node.

rough sketch:

![infobox](https://cloud.githubusercontent.com/assets/1084872/9397217/3ffc14c8-474f-11e5-9bb2-ea6f61ac4b70.png)

**Comment by jhpoelen** [comment]
@coding46 I took a first stab at the info boxes. I was hoping you could help merge your taxon info divs with the existing one in globi.js . Also, curious to hear thought on the current placements and user interactions: click to show, click to hide.

![screen shot 2015-08-26 at 7 53 20 pm](https://cloud.githubusercontent.com/assets/1084872/9511491/2ed3d1a4-4c2c-11e5-8d96-d7b172aed7d0.png)

**Comment by coding46** [comment]
Applied new view/style for the info box. Same as in result list.

**Comment by jhpoelen** [comment]
looks great @coding46 !

![screen shot 2015-08-28 at 7 18 19 pm](https://cloud.githubusercontent.com/assets/1084872/9560121/939c6d42-4db9-11e5-9faf-8f8f9f44e765.png)
