### ISSUE TITLE
visually highlight selected nodes and interactions in hairball

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions.github.io#49]
@mxweber suggested to visually highlight or bring forward the selected node and its connections in the hairball. This is to better see the local web of that specific node.

Perhaps we can do this by decreasing the alpha levels of non-selected nodes, links and names.

**Comment by coding46** [comment]
Reopen to discuss the attempt in 2f94fbb

**Comment by jhpoelen** [comment]
Please see comment here:
https://github.com/globalbioticinteractions/globalbioticinteractions.github.io/commit/2f94fbb6496d0397823010d618785d7a7528a18b#commitcomment-12907273

**Comment by jhpoelen** [comment]
On closer inspection, I noticed that of the source-target taxon pairs, only on selecting the source taxon, the target taxon names are shown. On selecting the target taxon name, the source taxon names are *not* shown. I think it would be great to have the highlight feature that you've built go both ways.

selecting _Pleuragramma antacticum_ produces:
![screen shot 2015-08-26 at 9 41 37 am](https://cloud.githubusercontent.com/assets/1084872/9499920/1b1288fe-4bd7-11e5-9af2-03600c8a2cd8.png)

selecting _Dapton capense_ , a source taxon of _Pleuragramma antacticum_ produces:
![screen shot 2015-08-26 at 9 46 04 am](https://cloud.githubusercontent.com/assets/1084872/9499982/88831bf6-4bd7-11e5-9d15-a04b79585722.png)
