### ISSUE TITLE
show instructions on "empty resultset" in interaction browser 

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions.github.io#53]
@katjaschulz suggested to include some instructions on what to do when an "empty resultset" is retrieved. 

![screen shot 2015-08-26 at 9 51 54 am](https://cloud.githubusercontent.com/assets/1084872/9500063/1c61c5ac-4bd8-11e5-8642-4acd9808502c.png)

**Comment by jhpoelen** [comment]
@mariestuder added some placeholder text for empty results. please let me know if you have any suggestions.

![screen shot 2015-08-26 at 7 55 26 pm](https://cloud.githubusercontent.com/assets/1084872/9511533/7bfbce8c-4c2c-11e5-9bae-135996a79c95.png)

**Comment by jhpoelen** [comment]
Please re-open this issue if you have suggestions on how to improve the text.

**Comment by mariestuder** [comment]
Looks fine.  Great improvement to have some feedback!
