### ISSUE TITLE
validation for iNaturalist record-backwardness

### ISSUE THREAD

**Issue by jhammock** [globalbioticinteractions/globalbioticinteractions.github.io#65]
I believe this happens with some regularity, eg:

https://www.inaturalist.org/observations/887896

iNat observers use a relationship field in reverse. I believe GloBI receives iNat data from a number of relationship data fields where each partner is expected to belong to a particular kingdom, (eg: animal and plant) and if the kingdoms are reversed, it's a good bet the relationship has been reversed. These might be easy to detect. What action should be taken at that point, I hesitate to suggest. A notification sent back to iNat? And/or automatic (provisional) reversal of the record in GloBI? 

opinions, @KatjaSchulz or @carrieseltzer ?

**Comment by KatjaSchulz** [comment]
When I reviewed the iNat interaction data a couple of years ago, I found lots of systematic problems like that. We fixed a bunch at the time, but trying to keep on top of them across the multitude of interaction fields has become overwhelming.  If iNat ever settles on a set of "official" interaction fields, I would be willing to participate in quality control.

When @jhpoelen was in DC, we talked about some general rules for flags that could help with quality control.  A rule that flags all records where insects are claimed to be hosts of plants would have caught this particular example.

**Comment by jhpoelen** [comment]
@KatjaSchulz Thanks for chiming in. Some notes of our DC discussion are available at  https://github.com/jhpoelen/eol-globi-data/wiki/Quality-Control . I hope we can come up with a method that is actionable and allow for the the dataset curator (the person that cares) with the dataset user (also, a person that cares) in addition to annotating suspicious records using a set of rules/ records compiled by experts such as yourself.

**Comment by jhpoelen** [comment]
@jhammock (and others) Happy to explore pragmatic approaches to getting more validation into GloBI to help capture/ signal/ message improvement suggestions to the relevant folks.

**Comment by jhpoelen** [comment]
@KatjaSchulz please see https://github.com/jhpoelen/eol-globi-data/issues/376 with a proposal on how to collect validation rules provided by experts and how to display interaction records that has refuting rules. Happy to hear comments if you have any.

**Comment by jhpoelen** [comment]
@jhammock I've recorded your disagreement with the interaction reported via https://www.inaturalist.org/observations/887896 in http://github.com/globalbioticinteractions/refuted-interaction-data . 

Over the years, I've encountered many errors in species interaction datasets, including those published in scholarly journals and iNaturalist observations. Since I can't expect that the original authors will correct their perceived mistakes, recording a disagreement via https://github.com/jhpoelen/eol-globi-data/issues/376 makes the statement explicit and clear.. 

The changes should propagate in a couple days.

**Comment by jhammock** [comment]
Certainly, this is a problem with many data sources. iNaturalist is distinct mostly in that it is a live dataset and there's some possibility of systemic correction, but that aught to take place at the source, I guess.

**Comment by jhpoelen** [comment]
Ideally, yes. iNaturalist could mine GloBI for disagreements for specific interactions and learn from it. That way, they could benefit from your expertise.
