### ISSUE TITLE
show language dependent common names

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions.github.io#70]
Currently, only English common names are shown. 

Suggest to show common names available for language version of GloBI. E.g., show "sea otter" for English and "Nutria marina" for Spanish.

fyi @AntarMijail

**Comment by jhpoelen** [comment]
English and Spanish common names are now shown in respective website language versions.

See attached screenshots.

![Screenshot from 2019-09-11 14-25-24](https://user-images.githubusercontent.com/1084872/64736851-76882300-d4a0-11e9-9235-5f9145dff1b3.png)
![Uploading Screenshot from 2019-09-11 14-25-05.png…]()

**Comment by AntarMijail** [comment]
Hi! 

In Spanish we don´t say "Nutria marina", it does not wrong make the distinction but it is not a common thing. We only use the Spanish word "Nutria" for the fresh and marine otters. I leave it to you, both ways are correct.

**Comment by jhpoelen** [comment]
The common names come from external sources via . In this case, the Spanish common name came from the Encyclopedia of Life via GloBI's taxon graph https://doi.org/10.5281/zenodo.1495265 .  I hope making the common names (if available) visible will help to make them better.
