### ISSUE TITLE
suggestion for real-time  database tracker

### ISSUE THREAD

**Issue by irynad** [globalbioticinteractions/globalbioticinteractions.github.io#8]
It was great to see Jorrit's presentation at UC Berkeley on Thursday. I am writing to follow up on the discussion and to suggest adding a feature that would allow users to see how many contributing databases are active at the moment of data search or download. This could be helpful in situations when major contributing databases are offline or in temporary maintenance. Their temporary absence from the pool of linked sources would result in potentially incomplete information for the user and depending on what the user needs, they may decide to check for a more comprehensive dataset later. Perhaps it could be something very simple like a counter showing the number of active databases relative to the number of total potentially available, possibly with the names of active databases (just for major databases, not individual pieces of information that may also change in time). Thanks again! Iryna

**Comment by jhpoelen** [comment]
hi @irynad - I am glad you liked the GloBI presentation and thanks for your suggestion. I have been thinking about ways to highlight issue with data sources to inform both data consumer and source curator. One way I thought of was to make a "source" page with the name of the data source, number of imported interactions, date of last access and a link to a list of log messages. Something like:

status | source | accessed at | warnings | errors | logs
---- | ---- | ---- | ---- | ---- | ---- | ----
:sunny: | GeMinA | 2015-01-12 |  9 | 0 | point to log url
:cloud: | SPIRE | 2015-02-12 | 9 | 3 | point to log url
... | ...| ... | ... | ... | ... | ...

Was this something you were imagining? If not, what would you change / add?

thx,
-jorrit

**Comment by jhpoelen** [comment]
@jhammock @cmungall any ideas on this?

**Comment by jhammock** [comment]
I like the format you propose above- particularly the meteorological symbols :)  I'm primarily wondering if it's practical/ a reasonable amount of effort...

**Comment by irynad** [comment]
The format above looks great. Definitely, keeping it as simple as possible in terms of what is the most feasible,  just to provide an idea of the pool of information available and not available at the moment.

**Comment by jhpoelen** [comment]
hi @irynad - Thanks again for the suggestion you made during my BIDS talk in Feb 2015. I finally got around to building a page that show the up-to-date status of the databases that GloBI known about. You can find the page here: http://www.globalbioticinteractions.org/status.html , I've also attached a screenshot of the page to this issue. Curious to hear your thoughts.

![partialstatuspage](https://cloud.githubusercontent.com/assets/1084872/22117860/686466b8-de2a-11e6-8aad-3cdb08f45cea.png)
