### ISSUE TITLE
interaction type infobox on mouse over / click  in interaction browser

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions.github.io#9]
as discussed with @jhammock and Michele Weber @mxweber :

To inform users with the definition of an interaction types (preys on, parasite of), an info box pops up on mouse over / mouse click. This info box contains a short description and link to definition in the relation ontology.

**Comment by jhpoelen** [comment]
interaction type info box includes the description (to be added) and termIRI as provided by http://api.globalbioticinteractions.org/interactionTypes .

**Comment by coding46** [comment]
Base implementation @see http://www.globalbioticinteractions.org/widget.html
