### ISSUE TITLE
Markdown language not producing expected results

### ISSUE THREAD

**Issue by EMTuckerLabUMMZ** [globalbioticinteractions/globalbioticinteractions.github.io#95]
I'm adding content to the page [globalbioticinteractions.github.io](https://github.com/globalbioticinteractions/globalbioticinteractions.github.io)/how-to.md
A number of things look fine on the preview (like the emojis and lists), but the actual webpage produces looks different and doesn't seem to render much of the markdown embedded. 
Not sure if if the issue discussed here helps: https://github.com/microsoft/vscode/issues/118905 
I'm not sure how to fix it, other than use less formatted text...

**Comment by EMTuckerLabUMMZ** [comment]
Other examples - Bulleted lists show in the preview, but not on he rendered web page. I've tried "-", "*", and "+" all of which should make bulleted lists (and do on the preview), but none show on the webpage. 
Is there something in the underlying framework files that needs to be activated for most common formatting to work?

**Comment by jhpoelen** [comment]
Thanks for sharing . . . hoping to have a look today. 

If it renders ok in the preview, please assume that your work is ok. Thanks for making all the improvements.

**Comment by EMTuckerLabUMMZ** [comment]
Additionally, parts of coding that look fine in preview, show some (not all) of the coding on web page. For example, in preview the "top of page" links look great. On the web page it shows: <p align="center"> Top of Page </p></a> (which is some of the coding, but not all of it). Same with the coding for the title/header at the top of the page...

**Comment by jhpoelen** [comment]
Thanks for sharing. Am in a workshop, hoping to have a look at the end of today.

**Comment by jhpoelen** [comment]
hey @EMTuckerLabUMMZ - 

I've added some minor edits for now. A little more styling via is needed/possible, but hoping to get to that later and focus on content for now. 

I've used ```<span id="some anchor"/>``` as a way to place anchors and ```[label](#some-archor)``` markdown to link them.

And, I've replaced the remaining ```:warning:``` with their UTF-8 emojis like ```⚠️``` . 

formatting issues aside, does the content look ok?

**Comment by jhpoelen** [comment]
ps @EMTuckerLabUMMZ your how-to page is looking really informative and inviting to me!

**Comment by EMTuckerLabUMMZ** [comment]
Thanks @jhpoelen :) I'm excited about creating this addition.
I think its mostly just the weird formatting issues: no bullet points, oddly sized text, lack of alignment capabilities... Great that you got the emoji thing fixed, but still strange it only likes it when selected from the popup menu... Also that the formatting on the main web page looks different from the preview on github. That makes it challenging to format things since it looks good on preview, but then does wacky thing on the web page and I need to wait for it to reprocess each time I make a theoretically minor change, lol. 
If the <span> style of things works better for this instance of page building, I'll try to use more of that..
Thanks and hope the workshop is going well!

**Comment by jhpoelen** [comment]
I agree that the formatting is weird. I can try to create a different page template that uses a different style sheet (css) - the structure of the page would be the same, but the formatting (e.g., numbering, font size) would change. 

thanks for being patient in dealing with these silly layout issues introduced by the GloBI website. 

Please don't hesitate to update or add info as I am trying to figure this out.

**Comment by jhpoelen** [comment]
@EMTuckerLabUMMZ I attempted to tweak the stylesheet for the how-to page. Please have a look and close this issue is the style looks ok. If not, please let me know what you feel should be changed.

**Comment by jhpoelen** [comment]
ps I also attempted to fix the image links you've added recently.

**Comment by EMTuckerLabUMMZ** [comment]
AH! That looks great @jhpoelen! Thank you! :)
Closing issue now...
